#!/usr/bin/env node
/**
 * Builds the Reverdle daily puzzle schedule.
 *
 * A puzzle is: one answer word (shown to the player) plus ROWS target
 * patterns. Each target pattern is guaranteed to be produced by EXACTLY ONE
 * word in the full guess dictionary, so every row has a single, unambiguous
 * solution. The solution word itself is always drawn from the common list so
 * the puzzle stays fair.
 *
 * Usage: node tools/generate.js
 * Writes: data/dict.js, data/puzzles.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ROWS = 4;
const read = (f) =>
  fs.readFileSync(path.join(ROOT, 'data', f), 'utf8')
    .split(/\s+/)
    .filter((w) => /^[a-z]{5}$/.test(w));

const GUESS = read('words-guess.txt');
const COMMON = read('words-common.txt');
const commonSet = new Set(COMMON);

// Standard Wordle scoring: 2 = green, 1 = yellow, 0 = grey.
function score(guess, answer) {
  const out = [0, 0, 0, 0, 0];
  const left = {};
  for (let i = 0; i < 5; i++) {
    if (guess[i] === answer[i]) out[i] = 2;
    else left[answer[i]] = (left[answer[i]] || 0) + 1;
  }
  for (let i = 0; i < 5; i++) {
    if (out[i] === 0 && left[guess[i]] > 0) {
      out[i] = 1;
      left[guess[i]]--;
    }
  }
  return out.join('');
}

// Higher = easier to deduce: greens pin a letter to a slot, yellows only hint.
const ease = (p) => 2 * (p.match(/2/g) || []).length + (p.match(/1/g) || []).length;

function unambiguousTargets(answer) {
  const byPattern = new Map();
  for (const w of GUESS) {
    const p = score(w, answer);
    let bucket = byPattern.get(p);
    if (!bucket) byPattern.set(p, (bucket = []));
    bucket.push(w);
  }
  const out = [];
  for (const [pattern, words] of byPattern) {
    // All-green is just the answer itself - no puzzle there.
    if (pattern === '22222') continue;
    if (words.length !== 1) continue;
    if (!commonSet.has(words[0])) continue;
    out.push({ pattern, word: words[0] });
  }
  return out.sort((a, b) => ease(b.pattern) - ease(a.pattern));
}

function mulberry32(a) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const puzzles = [];
for (const answer of COMMON) {
  const cand = unambiguousTargets(answer);
  if (cand.length < ROWS) continue;
  // Spread the rows evenly across the difficulty range, easiest first.
  const step = (cand.length - 1) / (ROWS - 1);
  const rows = [];
  for (let i = 0; i < ROWS; i++) rows.push(cand[Math.round(i * step)]);
  puzzles.push({ a: answer, r: rows.map((t) => [t.pattern, t.word]) });
}

// Fixed seed keeps the daily schedule stable across rebuilds.
const rand = mulberry32(20260101);
for (let i = puzzles.length - 1; i > 0; i--) {
  const j = Math.floor(rand() * (i + 1));
  [puzzles[i], puzzles[j]] = [puzzles[j], puzzles[i]];
}

const banner = '// Generated by tools/generate.js - do not edit by hand.\n';
fs.writeFileSync(
  path.join(ROOT, 'data', 'dict.js'),
  banner + 'const DICT = ' + JSON.stringify(GUESS) + ';\n'
);
fs.writeFileSync(
  path.join(ROOT, 'data', 'puzzles.js'),
  banner +
    'const LAUNCH_DATE = "2026-01-01";\n' +
    'const PUZZLES = ' +
    JSON.stringify(puzzles) +
    ';\n'
);

console.log(`${puzzles.length} puzzles (${(puzzles.length / 365).toFixed(1)} years)`);
console.log('sample:', JSON.stringify(puzzles[0]));
